-- Phase A, U1. Apply after the unchanged migrations 001–005.
begin;
create table public.terms (
  id text primary key check(id ~ '^[a-z0-9][a-z0-9-]{0,39}$'),
  title text not null check(length(title) between 1 and 100),
  status text not null check(status in ('active','archived-readable','closed')),
  created_at timestamptz not null default clock_timestamp()
);
create unique index one_active_term on public.terms(status) where status='active';
insert into public.terms(id,title,status) values('spring-2027','Spring 2027','active');
create function private.active_term() returns text
language sql stable security definer set search_path='' as $$
  select id from public.terms where status='active'
$$;
revoke all on function private.active_term() from public,anon;
grant execute on function private.active_term() to authenticated;

-- Instructions also belong to a term; keep their existing 1–6 assignment IDs.
do $$ declare t text; begin
  foreach t in array array['roster','assignments','attendance_sessions','attendance','group_sets','class_groups','group_memberships','grade_items','grades','announcements','lecture_files'] loop
    execute format('alter table public.%I add column term_id text not null default ''spring-2027'' references public.terms(id)',t);
    execute format('alter table public.%I alter column term_id set default private.active_term()',t);
  end loop;
end $$;
alter table private.student_previews add column term_id text not null default 'spring-2027' references public.terms(id);
alter table private.student_previews alter column term_id set default private.active_term();
alter table public.attendance drop constraint attendance_week_fkey;
alter table public.grades drop constraint grades_item_id_fkey;
alter table public.group_memberships drop constraint group_memberships_group_id_set_id_fkey;
alter table public.class_groups drop constraint class_groups_set_id_fkey;
alter table public.roster drop constraint roster_pkey, add primary key(term_id,uni);
alter table public.assignments drop constraint assignments_pkey, add primary key(term_id,id);
alter table public.attendance_sessions drop constraint attendance_sessions_pkey, add primary key(term_id,week);
alter table public.attendance drop constraint attendance_pkey, add primary key(term_id,uni,week),
  add foreign key(term_id,week) references public.attendance_sessions(term_id,week);
alter table public.group_sets drop constraint group_sets_pkey, add primary key(term_id,id);
alter table public.class_groups drop constraint class_groups_pkey, drop constraint class_groups_set_id_number_key,
  drop constraint class_groups_id_set_id_key, add primary key(term_id,id), add unique(term_id,set_id,number),
  add unique(term_id,id,set_id), add foreign key(term_id,set_id) references public.group_sets(term_id,id) on delete cascade;
alter table public.group_memberships drop constraint group_memberships_pkey, add primary key(term_id,set_id,uni),
  add foreign key(term_id,group_id,set_id) references public.class_groups(term_id,id,set_id) on delete cascade;
alter table public.grade_items add column code text;
update public.grade_items set code=case when id<=5 then 'M'||id when id=6 then 'FP' when id<=11 then 'Q'||(id-6) when id=12 then 'PA' else 'O'||(id-12) end;
alter table public.grade_items alter column code set not null, add unique(term_id,code), add unique(term_id,id),
  drop constraint grade_items_quiz_week_key, add unique(term_id,quiz_week);
alter table public.grade_items alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('public.grade_items','id'),(select max(id) from public.grade_items));
revoke all on sequence public.grade_items_id_seq from public,anon,authenticated;
alter table public.grades drop constraint grades_pkey, add primary key(term_id,uni,item_id),
  add foreign key(term_id,item_id) references public.grade_items(term_id,id);
alter table public.lecture_files drop constraint lecture_files_pkey, add primary key(term_id,id);
alter table public.announcements drop constraint announcements_pkey, add primary key(term_id,id);
alter table public.attendance_sessions drop constraint attendance_sessions_week_check,
  add check(week between 0 and 7), add column starts_at timestamptz, add column ends_at timestamptz,
  add check(ends_at is null or starts_at is null or ends_at>starts_at);
alter table public.lecture_files drop constraint lecture_files_week_check, add check(week between 0 and 7),
  add column release_at timestamptz, add column released boolean not null default true;
-- Existing notes remain posted. New teaching files can explicitly start unreleased.

create function private.actor_uni() returns text
language sql stable security definer set search_path='' as $$
  select coalesce((select uni from private.test_accounts where email=private.current_email()),
    case when private.current_email() like '%@columbia.edu' then split_part(private.current_email(),'@',1)
    else (select uni from private.student_accounts where email=private.current_email()) end)
$$;
create or replace function private.actor_role() returns text
language plpgsql stable security definer set search_path='' as $$
declare e text:=private.current_email(); r text;
begin
  if e is null then return 'unlisted'; end if;
  select role into r from public.allowlist where email=e;
  if r is not null then return r; end if;
  select role into r from private.test_accounts where email=e;
  if r is not null and private.active_term() is not null then return r; end if;
  if exists(select 1 from public.roster r join public.terms t on t.id=r.term_id
    where r.uni=private.actor_uni() and t.status in ('active','archived-readable')) then return 'student'; end if;
  return 'unlisted';
end $$;
create or replace function private.current_uni() returns text
language sql stable security definer set search_path='' as $$ select coalesce(private.preview_uni(),private.actor_uni()) $$;
create function private.current_term() returns text
language sql stable security definer set search_path='' as $$
  select coalesce(
    (select term_id from private.student_previews where user_id=auth.uid() and private.actor_role()='instructor'),
    case when private.actor_role() in ('instructor','grader','auditor')
      or exists(select 1 from private.test_accounts where email=private.current_email()) then private.active_term()
    else (select t.id from public.terms t join public.roster r on r.term_id=t.id
      where r.uni=private.actor_uni() and t.status in ('active','archived-readable')
      order by (t.status='active') desc,t.created_at desc,t.id desc limit 1) end)
$$;
create function private.can_read_term(p_term text) returns boolean
language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.terms t where t.id=p_term and (
    private.current_role() in ('instructor','grader') or
    (private.current_role()='auditor' and t.status='active') or
    (private.current_role()='student' and t.status in ('active','archived-readable') and (
      exists(select 1 from public.roster r where r.term_id=t.id and r.uni=private.current_uni()) or
      (t.status='active' and exists(select 1 from private.test_accounts a where a.role='student' and a.uni=private.current_uni()))))))
$$;
create or replace function private.assert_writable() returns void
language plpgsql security definer set search_path='' as $$
begin
  if private.preview_uni() is not null then raise exception 'Student preview is read-only. Exit preview before making changes.'; end if;
  if private.current_role()='student' and private.current_term() is distinct from private.active_term() then raise exception 'Archived term is read-only.'; end if;
end $$;
create function private.term_roster(p_term text) returns table(uni text,name text,email text,is_test boolean)
language sql stable security definer set search_path='' as $$
  select r.uni,r.name,r.uni||'@columbia.edu',false from public.roster r where r.term_id=p_term
    and not exists(select 1 from public.allowlist a where a.role in ('auditor','grader','instructor') and
      (a.email=r.uni||'@columbia.edu' or exists(select 1 from private.student_accounts s where s.email=a.email and s.uni=r.uni)))
  union all select t.uni,'Test student '||t.uni,null::text,true from private.test_accounts t
    where p_term=private.active_term() and t.role='student' and t.uni is not null
      and not exists(select 1 from public.roster r where r.term_id=p_term and r.uni=t.uni)
$$;
create or replace function private.class_roster() returns table(uni text,name text,email text,is_test boolean)
language sql stable security definer set search_path='' as $$ select * from private.term_roster(private.current_term()) $$;
-- Access is a read operation, including for former students and preview sessions.
create or replace function public.get_access() returns jsonb
language plpgsql stable security definer set search_path='' as $$
declare e text:=private.current_email(); u text:=private.current_uni(); r text:=private.current_role(); v text:=private.preview_uni(); t text:=private.current_term(); n text;
begin
  if e is null then raise exception 'Sign in with a verified Columbia Google account.'; end if;
  select name into n from private.term_roster(t) where uni=v;
  return jsonb_build_object('email',e,'uni',u,'role',r,'actor_role',private.actor_role(),
    'term_id',t,'read_only',v is not null or (select status<>'active' from public.terms where id=t),
    'needs_uni',e like '%@gsb.columbia.edu' and u is null and r='unlisted',
    'view_as',case when v is null then null else jsonb_build_object('uni',v,'name',coalesce(n,v),'term_id',t) end);
end $$;
drop function public.set_student_preview(text);
create function public.set_student_preview(target_uni text default null,p_term text default null) returns jsonb
language plpgsql security definer set search_path='' as $$
declare t text:=coalesce(p_term,private.active_term());
begin
  -- Preview controls check the real actor, so an instructor can switch or exit directly.
  if private.actor_role()<>'instructor' then raise exception 'Instructor access required.'; end if;
  if target_uni is null then
    delete from private.student_previews where user_id=auth.uid(); return public.get_access();
  end if;
  -- Only readable terms can be previewed; ordinary writes still reject archived terms.
  if not exists(select 1 from public.terms where id=t and status in ('active','archived-readable')) or
    not exists(select 1 from private.term_roster(t) where uni=target_uni) then raise exception 'Student not found.'; end if;
  insert into private.student_previews(user_id,uni,term_id) values(auth.uid(),target_uni,t)
    on conflict(user_id) do update set uni=excluded.uni,term_id=excluded.term_id,started_at=now();
  return public.get_access();
end $$;
create or replace function public.replace_roster(rows jsonb) returns integer
language plpgsql security definer set search_path='' as $$
declare n integer; t text:=private.active_term();
begin
  perform private.assert_writable(); perform private.require_instructor();
  if rows is null or jsonb_typeof(rows)<>'array' or jsonb_array_length(rows) not between 1 and 5000 then raise exception 'Provide 1 to 5000 valid roster rows.'; end if;
  if exists(select 1 from jsonb_to_recordset(rows) as x(uni text,name text) where uni is null or uni !~ '^[a-z]{1,8}[0-9]{1,8}$' or length(coalesce(name,''))>200) then raise exception 'Invalid roster row.'; end if;
  perform pg_advisory_xact_lock(hashtextextended('roster:'||t,0));
  delete from public.roster where term_id=t;
  insert into public.roster(term_id,uni,name) select t,uni,coalesce(name,'') from jsonb_to_recordset(rows) as x(uni text,name text);
  get diagnostics n=row_count; return n;
end $$;
create or replace function public.set_session_date(p_week integer,p_date date) returns void
language plpgsql security definer set search_path='' as $$
begin
  perform private.assert_writable(); perform private.require_instructor();
  update public.attendance_sessions set date=p_date where term_id=private.active_term() and week=p_week;
  if not found then raise exception 'Invalid session.'; end if;
end $$;
create function public.set_session_times(p_week integer,p_start timestamptz,p_end timestamptz) returns void
language plpgsql security definer set search_path='' as $$
begin
  perform private.assert_writable(); perform private.require_instructor();
  update public.attendance_sessions set starts_at=p_start,ends_at=p_end,
    date=case when p_start is null then date else (p_start at time zone 'America/New_York')::date end
    where term_id=private.active_term() and week=p_week;
  if not found then raise exception 'Invalid session.'; end if;
end $$;
create or replace function public.save_attendance(p_week integer,entries jsonb) returns void
language plpgsql security definer set search_path='' as $$
declare e record; q integer; t text:=private.active_term();
begin
  perform private.assert_writable(); perform private.require_grader();
  if not exists(select 1 from public.attendance_sessions where term_id=t and week=p_week) then raise exception 'Invalid session.'; end if;
  if entries is null or jsonb_typeof(entries)<>'array' or jsonb_array_length(entries)>5000 then raise exception 'Invalid attendance rows.'; end if;
  for e in select * from jsonb_to_recordset(entries) as x(uni text,status text) order by uni loop
    perform pg_advisory_xact_lock(hashtextextended(t||':student:'||e.uni,0));
    if not exists(select 1 from private.term_roster(t) r where r.uni=e.uni) then raise exception 'Unknown UNI: %',e.uni; end if;
    select i.quiz_week into q from public.grade_items i join public.grades g on g.term_id=i.term_id and g.item_id=i.id
      where i.term_id=t and g.uni=e.uni and i.quiz_week=p_week;
    if e.status is null then
      delete from public.attendance where term_id=t and uni=e.uni and week=p_week;
      if q is not null then insert into public.attendance(term_id,uni,week,status,source_quiz) values(t,e.uni,p_week,'present',q); end if;
    else insert into public.attendance(term_id,uni,week,status,source_quiz,manual_override) values(t,e.uni,p_week,e.status,q,true)
      on conflict(term_id,uni,week) do update set status=excluded.status,source_quiz=excluded.source_quiz,manual_override=true; end if;
  end loop;
end $$;
create or replace function public.save_grades(entries jsonb) returns void
language plpgsql security definer set search_path='' as $$
declare e record; maximum numeric; q integer; t text:=private.active_term();
begin
  perform private.assert_writable(); perform private.require_grader();
  if entries is null or jsonb_typeof(entries)<>'array' or jsonb_array_length(entries)>80000 then raise exception 'Invalid grade rows.'; end if;
  for e in select * from jsonb_to_recordset(entries) as x(uni text,item_id integer,score numeric) order by uni,item_id loop
    perform pg_advisory_xact_lock(hashtextextended(t||':student:'||e.uni,0));
    if not exists(select 1 from private.term_roster(t) r where r.uni=e.uni) then raise exception 'Unknown UNI: %',e.uni; end if;
    select max_points,quiz_week into maximum,q from public.grade_items where term_id=t and id=e.item_id;
    if maximum is null or (e.score is not null and (e.score<0 or e.score>maximum or e.score::text in ('NaN','Infinity','-Infinity') or e.score<>round(e.score,2))) then raise exception 'Invalid score for item %.',e.item_id; end if;
    if e.score is null then delete from public.grades where term_id=t and uni=e.uni and item_id=e.item_id;
    else insert into public.grades(term_id,uni,item_id,score) values(t,e.uni,e.item_id,e.score)
      on conflict(term_id,uni,item_id) do update set score=excluded.score; end if;
    if q is not null then
      if e.score is null then
        delete from public.attendance where term_id=t and uni=e.uni and week=q and source_quiz=q and not manual_override;
        update public.attendance set source_quiz=null where term_id=t and uni=e.uni and week=q;
      else insert into public.attendance(term_id,uni,week,status,source_quiz) values(t,e.uni,q,'present',q)
        on conflict(term_id,uni,week) do update set source_quiz=q,
          status=case when public.attendance.manual_override then public.attendance.status else 'present' end;
      end if;
    end if;
  end loop;
end $$;
create or replace function public.release_grade_item(p_item integer,p_released boolean) returns void
language plpgsql security definer set search_path='' as $$
begin
  perform private.assert_writable(); perform private.require_instructor();
  update public.grade_items set released=p_released where term_id=private.active_term() and id=p_item;
  if not found then raise exception 'Invalid item.'; end if;
end $$;
create or replace function public.create_group_set(p_title text,p_count integer,p_max integer,p_deadline timestamptz default null) returns uuid
language plpgsql security definer set search_path='' as $$
declare v_id uuid; t text:=private.active_term();
begin
  perform private.assert_writable(); perform private.require_instructor();
  if p_count is null or p_count not between 1 and 100 then raise exception 'Choose 1 to 100 groups.'; end if;
  insert into public.group_sets(term_id,title,max_size,deadline) values(t,trim(p_title),p_max,p_deadline) returning id into v_id;
  insert into public.class_groups(term_id,set_id,number) select t,v_id,generate_series(1,p_count); return v_id;
end $$;
create or replace function public.update_group_set(p_set uuid,p_open boolean,p_deadline timestamptz) returns void
language plpgsql security definer set search_path='' as $$
begin
  perform private.assert_writable(); perform private.require_instructor();
  update public.group_sets set is_open=p_open,deadline=p_deadline where term_id=private.active_term() and id=p_set;
  if not found then raise exception 'Group set not found.'; end if;
end $$;
create or replace function public.choose_group(p_set uuid,p_group uuid default null,p_uni text default null) returns void
language plpgsql security definer set search_path='' as $$
declare s public.group_sets; u text; r text:=private.current_role(); t text:=private.active_term();
begin
  perform private.assert_writable();
  if r not in ('student','instructor') then raise exception 'Class access required.'; end if;
  u:=case when r='instructor' then p_uni else private.current_uni() end;
  if r='student' and p_uni is not null and p_uni is distinct from u then raise exception 'You can only change your own group.'; end if;
  if u is null or not exists(select 1 from private.term_roster(t) where uni=u) then raise exception 'Student not found.'; end if;
  select * into s from public.group_sets where term_id=t and id=p_set for update;
  if not found then raise exception 'Group set not found.'; end if;
  if r='student' and (not s.is_open or (s.deadline is not null and clock_timestamp()>=s.deadline)) then raise exception 'Sign-up is closed.'; end if;
  if p_group is null then delete from public.group_memberships where term_id=t and set_id=p_set and uni=u; return; end if;
  if not exists(select 1 from public.class_groups where term_id=t and id=p_group and set_id=p_set) then raise exception 'Group not found in this set.'; end if;
  if exists(select 1 from public.group_memberships where term_id=t and set_id=p_set and uni=u and group_id=p_group) then return; end if;
  if (select count(*) from public.group_memberships m join private.term_roster(t) r on r.uni=m.uni where m.term_id=t and m.group_id=p_group)>=s.max_size then raise exception 'This group is full.'; end if;
  insert into public.group_memberships(term_id,set_id,group_id,uni) values(t,p_set,p_group,u)
    on conflict(term_id,set_id,uni) do update set group_id=excluded.group_id;
end $$;

-- One projection serves all callers. Every subquery carries its term and role predicate.
create function private.term_snapshot(t text,u text,r text) returns jsonb
language sql stable security definer set search_path='' as $$
select jsonb_build_object(
  'term_id',t,
  'sessions',(select coalesce(jsonb_agg(s order by week),'[]') from public.attendance_sessions s where s.term_id=t),
  'attendance',(select coalesce(jsonb_agg(jsonb_build_object('uni',a.uni,'week',a.week,'status',a.status,
    'source_quiz',case when r in ('instructor','grader') or i.released then a.source_quiz else null end,
    'manual_override',case when r in ('instructor','grader') or i.released then a.manual_override else null end) order by a.week),'[]')
    from public.attendance a left join public.grade_items i on i.term_id=a.term_id and i.quiz_week=a.source_quiz
    where a.term_id=t and (r in ('instructor','grader') or (r='student' and a.uni=u))),
  'items',(select coalesce(jsonb_agg(i order by id),'[]') from public.grade_items i where i.term_id=t and (r in ('instructor','grader') or (r='student' and i.released))),
  'grades',(select coalesce(jsonb_agg(g),'[]') from public.grades g join public.grade_items i on i.term_id=g.term_id and i.id=g.item_id
    where g.term_id=t and (r in ('instructor','grader') or (r='student' and g.uni=u and i.released))),
  'sets',(select coalesce(jsonb_agg(s order by created_at),'[]') from public.group_sets s where s.term_id=t and r in ('instructor','grader','student')),
  'groups',(select coalesce(jsonb_agg(g order by number),'[]') from public.class_groups g where g.term_id=t and r in ('instructor','grader','student')),
  'members',(select coalesce(jsonb_agg(jsonb_build_object('set_id',m.set_id,'group_id',m.group_id,
    'uni',case when r in ('instructor','grader') or m.uni=u then m.uni else null end,
    'name',case when r in ('instructor','grader') or exists(select 1 from public.group_memberships mine where mine.term_id=t and mine.uni=u and mine.group_id=m.group_id) then coalesce(nullif(c.name,''),'Student') else null end,
    'email',case when r='instructor' or (r='student' and exists(select 1 from public.group_memberships mine where mine.term_id=t and mine.uni=u and mine.group_id=m.group_id)) then c.email else null end)),'[]')
    from public.group_memberships m join private.term_roster(t) c on c.uni=m.uni where m.term_id=t and r in ('instructor','grader','student')),
  'assignments',(select coalesce(jsonb_agg(a order by id),'[]') from public.assignments a where a.term_id=t and (r in ('instructor','grader','student') or (r='auditor' and a.auditor_visible))),
  'files',(select coalesce(jsonb_agg(f order by created_at),'[]') from public.lecture_files f where f.term_id=t and
    (r in ('instructor','grader') or ((r='student' or (r='auditor' and f.auditor_visible)) and (f.released or f.release_at<=now())))),
  'announcements',(select coalesce(jsonb_agg(a order by created_at desc,id),'[]') from public.announcements a where a.term_id=t and r in ('instructor','grader','student','auditor'))
) || case when r in ('instructor','grader') then jsonb_build_object('roster',
  (select coalesce(jsonb_agg(case when r='grader' then jsonb_build_object('uni',c.uni,'name',c.name) else to_jsonb(c) end order by c.uni),'[]') from private.term_roster(t) c)) else '{}'::jsonb end
$$;
create or replace function private.student_snapshot(u text) returns jsonb
language sql stable security definer set search_path='' as $$
  select private.term_snapshot(private.current_term(),u,'student') where private.can_read_term(private.current_term())
$$;
drop function public.class_data();
create function public.class_data(p_term text default null) returns jsonb
language plpgsql stable security definer set search_path='' as $$
declare t text:=coalesce(p_term,private.current_term()); r text:=private.current_role();
begin
  if not private.can_read_term(t) then raise exception 'Class access required for this term.'; end if;
  return private.term_snapshot(t,private.current_uni(),r);
end $$;
-- Preview reads remain pinned to its selected term.
create or replace function public.view_as_student(target_uni text) returns jsonb
language plpgsql stable security definer set search_path='' as $$
begin
  if private.actor_role()<>'instructor' or private.preview_uni() is distinct from target_uni or target_uni is null then raise exception 'Start the read-only student preview first.'; end if;
  return private.student_snapshot(target_uni);
end $$;
create or replace function public.link_student_account(p_email text,p_uni text) returns void
language plpgsql security definer set search_path='' as $$
begin
  perform private.assert_writable(); perform private.require_instructor();
  if p_uni is null then delete from private.student_accounts where email=lower(trim(p_email)); return; end if;
  if not exists(select 1 from public.roster where term_id=private.active_term() and uni=lower(trim(p_uni))) then raise exception 'Student not found on roster.'; end if;
  insert into private.student_accounts(email,uni) values(lower(trim(p_email)),lower(trim(p_uni))) on conflict(email) do update set uni=excluded.uni;
end $$;

-- Rebuild only course-term policies. Global identity, allowlist, and storage guards stay intact.
do $$ declare p record; begin
  for p in select tablename,policyname from pg_policies where schemaname='public' and tablename in
    ('roster','assignments','attendance_sessions','attendance','group_sets','class_groups','group_memberships','grade_items','grades','announcements','lecture_files') loop
    execute format('drop policy %I on public.%I',p.policyname,p.tablename);
  end loop;
end $$;
alter table public.terms enable row level security;
revoke all on public.terms from public,anon,authenticated;
grant select(id,title,status,created_at) on public.terms to authenticated;
create policy terms_read on public.terms for select to authenticated using(private.can_read_term(id));
create trigger preview_guard before insert or update or delete on public.terms for each row execute function private.block_preview_write();
create trigger terms_audit after insert or update or delete on public.terms for each row execute function private.audit_class_change();
create policy roster_read on public.roster for select to authenticated using(private.current_role()='instructor' and private.can_read_term(term_id));
create policy sessions_read on public.attendance_sessions for select to authenticated using(private.can_read_term(term_id));
create policy attendance_read on public.attendance for select to authenticated using(private.current_role() in ('instructor','grader') and private.can_read_term(term_id));
create policy sets_read on public.group_sets for select to authenticated using(private.current_role() in ('student','instructor') and private.can_read_term(term_id));
create policy groups_read on public.class_groups for select to authenticated using(private.current_role() in ('student','instructor') and private.can_read_term(term_id));
create policy memberships_read on public.group_memberships for select to authenticated using(private.can_read_term(term_id) and (private.current_role()='instructor' or (private.current_role()='student' and uni=private.current_uni())));
create policy items_read on public.grade_items for select to authenticated using(private.can_read_term(term_id) and (private.current_role() in ('instructor','grader') or (private.current_role()='student' and released)));
create policy grades_read on public.grades for select to authenticated using(private.can_read_term(term_id) and (private.current_role() in ('instructor','grader') or (private.current_role()='student' and uni=private.current_uni() and exists(select 1 from public.grade_items i where i.term_id=grades.term_id and i.id=item_id and i.released))));
create policy assignment_read on public.assignments for select to authenticated using(private.can_read_term(term_id) and (private.current_role() in ('instructor','grader','student') or (private.current_role()='auditor' and auditor_visible)));
create policy lecture_read on public.lecture_files for select to authenticated using(private.can_read_term(term_id) and
  (private.current_role() in ('instructor','grader') or ((private.current_role()='student' or (private.current_role()='auditor' and auditor_visible)) and (released or release_at<=now()))));
create policy announcements_read on public.announcements for select to authenticated using(private.can_read_term(term_id));
do $$ declare t text; begin
  foreach t in array array['assignments','lecture_files','announcements'] loop
    execute format('create policy instructor_insert on public.%I for insert to authenticated with check(private.current_role()=''instructor'' and term_id=private.active_term())',t);
    execute format('create policy instructor_update on public.%I for update to authenticated using(private.current_role()=''instructor'' and term_id=private.active_term()) with check(private.current_role()=''instructor'' and term_id=private.active_term())',t);
    execute format('create policy instructor_delete on public.%I for delete to authenticated using(private.current_role()=''instructor'' and term_id=private.active_term())',t);
  end loop;
end $$;
-- No browser may retag existing data into another term.
revoke all on public.assignments,public.lecture_files from public,anon,authenticated;
grant select,delete on public.assignments,public.lecture_files to authenticated;
grant insert(id,title,due,points,description,deliverable,grading,auditor_visible),update(title,due,points,description,deliverable,grading,auditor_visible) on public.assignments to authenticated;
grant insert(week,title,storage_path,auditor_visible,release_at,released),update(week,title,auditor_visible,release_at,released) on public.lecture_files to authenticated;

revoke all on function private.actor_uni(),private.current_term(),private.can_read_term(text),private.term_roster(text),private.term_snapshot(text,text,text) from public,anon,authenticated;
grant execute on function private.current_term(),private.can_read_term(text) to authenticated;
revoke all on function public.set_student_preview(text,text),public.set_session_times(integer,timestamptz,timestamptz),public.class_data(text) from public,anon;
grant execute on function public.set_student_preview(text,text),public.set_session_times(integer,timestamptz,timestamptz),public.class_data(text) to authenticated;
commit;
